name: MapmakerUtilitiesReloaded
version: '${project.version}'
main: me.hapyl.mmu3.Main
api-version: 1.18
softdepend: [ EternaAPI ]
authors: [ hapyl ]
description: A utilities plugin for mapmakers by mapmakers.
